language: objective-c 

osx_image: xcode7

before_install: 
- brew update; brew update 
- brew outdated xctool || brew upgrade xctool 
- gem install cocoapods -v 0.39.0

before_script: # Find iPhone 6s with iOS 9.0 UDID 
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6s (9.0)" | awk -F '[\[]' '{print $2}' | sed 's/.$//'` 
- echo $IOS_SIMULATOR_UDID 
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
- xcodebuild
- workspace NextGen/NextGen.xcworkspace 
- scheme NextGen 
- destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.0' test > build.log && exit ${PIPESTATUS[0]}

after_failure:
- tail -n 500 build.log
